auth_enabled: false

server:
  http_listen_port: 3100

  grpc_server_max_recv_msg_size: 104857600  # 100 Mb
  grpc_server_max_send_msg_size: 104857600  # 100 Mb
  http_server_write_timeout: 5m

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

ingester:
  max_transfer_retries: 0
  concurrent_flushes: 4
  flush_op_timeout: 1m

  chunk_idle_period: 10s
  chunk_block_size: 262144
  chunk_target_size: 1536000
  chunk_encoding: snappy
  chunk_retain_period: 0s
  max_chunk_age: 1h
#  wal:
#    dir: /loki/wal

ingester_client:
  grpc_client_config:
    max_recv_msg_size: 52428800  # 50 mb
    max_send_msg_size: 52428800  # 50 mb

limits_config:
  reject_old_samples: false
  enforce_metric_name: true
  max_query_series: 100000

  retention_period: 744h
  ingestion_rate_mb: 100
  ingestion_burst_size_mb: 30
  per_stream_rate_limit: "150MB"

  split_queries_by_interval: 15m

  max_streams_per_user: 0
  max_global_streams_per_user: 0

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v12
      index:
        prefix: index_
        period: 24h

#auth_enabled: false
#
#server:
#  http_listen_port: 3100
#  log_level: debug
#
#ingester:
#  lifecycler:
#    address: 127.0.0.1
#    ring:
#      kvstore:
#        store: inmemory
#      replication_factor: 1
#    final_sleep: 0s
#  chunk_idle_period: 5m
#  chunk_retain_period: 0s
#  wal:
#
#
#schema_config:
#  configs:
#  - from: 2020-05-15
#    store: boltdb
#    object_store: filesystem
#    schema: v11
#    index:
#      prefix: index_
#      period: 168h
#
#storage_config:
#  boltdb:
#    directory: /loki/index
#
#  filesystem:
#    directory: /loki/chunks
#
#limits_config:
#  enforce_metric_name: false
#  reject_old_samples: true
#  reject_old_samples_max_age: 168h
